name: Release the app

on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        environment: Development
        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy

            - name: Setup Node.js
              uses: actions/setup-node@v3.2.0
              with:
                  node-version: '16.x'

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev \
                    webkit2gtk-4.0 libappindicator3-dev \
                    librsvg2-dev patchelf libdbus-1-dev \
                    pkg-config

            - name: Fetch Node.js Dependencies
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true

            - name: Build Release version
              run: pnpm build

            - name: Release AppImage
              uses: ncipollo/release-action@v1
              with:
                  artifacts: './src-tauri/target/release/bundle/appimage/*.AppImage'
                  token: ${{ secrets.GITHUB_TOKEN }}
